server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      enable_lazy_load_no_trans: true

  datasource:
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.96.47.115:3306/wechatPublicaAccount?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initial-size: 5
    max-active: 20
    min-idle: 5
    max-idle: 20
    max-wait: 30000
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true